// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTZ2tGsFYAhtnIQgQc7iMwsuGgybicSzc',
    appId: '1:207310636692:web:ca6996592887c7a7a45681',
    messagingSenderId: '207310636692',
    projectId: 'arounstore-2b00e',
    authDomain: 'arounstore-2b00e.firebaseapp.com',
    storageBucket: 'arounstore-2b00e.firebasestorage.app',
    measurementId: 'G-G37EJY90MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwmk-PnMwOnWZfaAIhfrM_Ws62vjFn6LU',
    appId: '1:207310636692:android:7d7ea676f7efb88da45681',
    messagingSenderId: '207310636692',
    projectId: 'arounstore-2b00e',
    storageBucket: 'arounstore-2b00e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5J8Ec7fUYZeS66A0NSPqJuzK9qUxMh6k',
    appId: '1:207310636692:ios:8bec4a1e1ee4e5a0a45681',
    messagingSenderId: '207310636692',
    projectId: 'arounstore-2b00e',
    storageBucket: 'arounstore-2b00e.firebasestorage.app',
    iosBundleId: 'com.example.arunstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5J8Ec7fUYZeS66A0NSPqJuzK9qUxMh6k',
    appId: '1:207310636692:ios:8bec4a1e1ee4e5a0a45681',
    messagingSenderId: '207310636692',
    projectId: 'arounstore-2b00e',
    storageBucket: 'arounstore-2b00e.firebasestorage.app',
    iosBundleId: 'com.example.arunstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTZ2tGsFYAhtnIQgQc7iMwsuGgybicSzc',
    appId: '1:207310636692:web:a57efe3ff99769f4a45681',
    messagingSenderId: '207310636692',
    projectId: 'arounstore-2b00e',
    authDomain: 'arounstore-2b00e.firebaseapp.com',
    storageBucket: 'arounstore-2b00e.firebasestorage.app',
    measurementId: 'G-V6JLQ6KLJV',
  );
}
